# Test your FastAPI endpoints
# Todo work out how this works - seems to have a built in tester that is nicer than Pytest
GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
