"""Add filter table description

Revision ID: 7e3883870cf4
Revises: f8f893e20221
Create Date: 2025-11-27 22:15:49.866629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3883870cf4'
down_revision: Union[str, Sequence[str], None] = 'f8f893e20221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filters', 'description')
    # ### end Alembic commands ###
