"""Add repeating task/project support 2

Revision ID: 80286e5d7bf1
Revises: 
Create Date: 2025-11-28 19:44:58.250758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80286e5d7bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('type', sa.Enum('project', 'area', name='projecttypes'), nullable=False),
    sa.Column('parent_project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='taskandprojectstatuses'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('deadline_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('repeat_interval_type', sa.Enum('intervalFromLastCompletedDate', 'intervalFromRepeatStartdate', name='repeatintervaltype'), nullable=True),
    sa.Column('repeat_interval', sa.Interval(), nullable=True),
    sa.Column('repeat_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('repeat_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskfilters',
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='taskandprojectstatuses'), nullable=False),
    sa.Column('deadline_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('repeat_interval_type', sa.Enum('intervalFromLastCompletedDate', 'intervalFromRepeatStartdate', name='repeatintervaltype'), nullable=True),
    sa.Column('repeat_interval', sa.Interval(), nullable=True),
    sa.Column('repeat_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('repeat_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('coalesce(project_id , parent_task_id) is not null'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('taskfilters')
    op.drop_table('projects')
    # ### end Alembic commands ###
