"""refactor database design to have common fields shared accross models aligned

Revision ID: baac0f3bc849
Revises:
Create Date: 2025-11-25 18:15:17.680171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "baac0f3bc849"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasklist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("deadline_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_started", "in_progress", "completed", name="taskandprojectstatuses"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "views",
        sa.Column(
            "rules_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started", "in_progress", "completed", name="taskandprojectstatuses"
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("deadline_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("tasklist_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tasklist_id"],
            ["tasklist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("views")
    op.drop_table("tasklist")
    op.drop_table("groups")
    # ### end Alembic commands ###
